### ISSUE TITLE
a question about the objective function

### ISSUE THREAD

**Issue by zorrocai** [CPJKU/deep_lda#1]
could you please explain about  "compute_conv" function ?
what does “compute class covariance matrix for group" mean?

**Comment by dmatte** [comment]
The function estimates the covariance for a certain class.
This is required in LDA to compute for example the within class scatter S_w.
The variable group is in this case the class label (for our test sets {0, ..., 9}).
As we need to compute the covariance matrix for all the classes we define the function "compute_cov"
and then loop over all classes using the theano scan function.

covs_t is then a list (matrix) containing the 10 individual class covariance matrices.
To compute the within-class-scatter Sw,
we can simply take the mean of this matrix along the first axis.
`Sw_t = T.mean(covs_t, axis=0)`

**Comment by zorrocai** [comment]
one more thing I couldn't understand is that why the time consumed for one epcho on mnist is nearly one hour based on lasagne.Is it maybe caused by the cudnn version? my cudnn version is 7,and the lasagne's recommended cudnn version is 5.

**Comment by dmatte** [comment]
I just tried it again. This is what I get after one epoch of mnist:
```
LDA-Eigenvalues (Train): [ 2.08  2.53  3.02  3.43  3.62  4.21  5.59  6.78  7.5 ]
Ratio min(eigval)/max(eigval): 0.277, Mean(eigvals): 4.307
Epoch 1 of 100 took 76.862s
  lr: 0.10000
  costs_tr -0.29249 (94.192), costs_val -2.45143 (94.740), tr/val 1.006
```
Are you sure that your theanorc is configured to use the GPU?
And your newer cudnn version shouldn't make it slower.

**Comment by zorrocai** [comment]
Thanks.
In .theanorc,I have set device=gpu0, and I monitor it runing process with GPU.
There is my one epoch of minst.it took 7022.671s,which is unbearable,and confused me a lot.I couldn't find where is the problem.
![screenshot from 2018-04-13 18 18 21](https://user-images.githubusercontent.com/24424749/38729934-3b17e778-3f47-11e8-97d1-28ee4d4995af.png)

**Comment by dmatte** [comment]
Could it be the debug mode?
> (Pdb) c

Otherwise, I don't have an idea what the problem could be.

**Comment by zorrocai** [comment]
Not causing by the debug mode which is used for comprehending the "objective" function.
I just ran the mnist in the examples carried by Lasagne. The cnn architecture on mnist consumes 10662.93s for  one epoch,while the mlp framework on mnist costs only 29.709s for one epoch, GPU are uesd for both conditions. The contrastive experiments may show that there is something problem with Lasagne's support for the cnn architecture.

**Comment by zorrocai** [comment]
the time problem has been solved. It caused by the "optimizer = None" in ~/.theanorc. This line makes the calculation back to cpu,though the data have been loaded in gpu.

**Comment by dmatte** [comment]
Ok, this was obviously very bad for performance.
I consider this issue as fixed then.

**Comment by RoyiAvital** [comment]
@dmatte ,
Where do you use the gradient in your code?
I mean the derivation as in your appendix.

Or do you rely on Auto Grad?

**Comment by zorrocai** [comment]
theano is with auto grad

**Comment by RoyiAvital** [comment]
@zorrocai , Have you verified its Gradient matches your Appendix?

**Comment by zorrocai** [comment]
sorry, I have not.
